services:
  clash:
    image: laoyutang/clash-and-dashboard
    container_name: clash-and-dashboard
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "8080:8080"
    restart: unless-stopped