{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "idekube.rabbitmq.fullname" . }}
  labels:
    {{- include "idekube.labels" . | nindent 4 }}
    app.kubernetes.io/component: message-broker
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
  selector:
    {{- include "idekube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: message-broker
{{- end }}