{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "idekube.rbac.fullname" . }}
  labels:
    {{- include "idekube.rbac.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rbac.service.type }}
  ports:
    - port: {{ .Values.rbac.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "idekube.rbac.selectorLabels" . | nindent 4 }}
{{- end }}
