apiVersion: v1
kind: Secret
metadata:
  name: idekube-secrets
  labels:
    {{- include "idekube.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
