# Patch for Secret - override access key and secret key
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
stringData:
  rustfs-access-key: "rustfsadmin"
  rustfs-secret-key: "rustfsadmin"