# rustfs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  labels:
    app: rustfs
    component: objectstorage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # storageClassName: standard
