apiVersion: v1
kind: ConfigMap
metadata:
  name: angos-config
data:
  config.toml: |
    [server]
    bind_address = "0.0.0.0"
    port = 5000

    [blob_store.fs]
    root_dir = "/data"

    [ui]
    enabled = true
    name = "My Registry"

    [auth.identity.admin]
    username = "admin"
    password = "$argon2i$v=19$m=4096,t=3,p=1$c29tZXNhbHQ$iWh06vD8Fy27wf9npn6FXWiCX4K6pW6Ue1Bnzz07Z8A"

    [global.access_policy]
    default_allow = false
    rules = [
      "identity.username != null"
    ]