apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: angos
  - path: pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: angos-data
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: angos-config