apiVersion: v1
kind: ConfigMap
metadata:
  name: angos-config
  labels:
    app: angos
    component: registry
data:
  config.toml: |
    [server]
    bind_address = "0.0.0.0"
    port = 5000

    [blob_store.fs]
    root_dir = "/data"

    [ui]
    enabled = true
    name = "My Registry"

    [auth.identity.admin]
    username = "admin"
    password = "$argon2i$v=19$m=4096,t=3,p=1$c29tZXNhbHQ$LogzcRQW8F6bOiq8H076gugMjycWzkEVY+QLe2FpNGs"

    [global.access_policy]
    default_allow = false
    rules = [
      "identity.username != null"
    ]