apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - angos-configmap.yaml
  - angos-service.yaml
  - angos-statefulset.yaml
  - angos-pvc.yaml
  - angos-ingress.yaml

labels:
  - pairs:
      app: angos
      component: registry
